CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = no
ORYX_ENABLE = no
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
UNICODEMAP_ENABLE = yes
OS_DETECTION_ENABLE = yes

SRC += keycode_handler.c
SRC += ezovrd.c
SRC += eztd.c
